orgs:
  operate-first:
    admins:
      - durandom
      - goern
      - HumairAK
      - sesheta
      - tumido
    billing_email: mhild@redhat.com
    company: ""
    default_repository_permission: read
    description: Open-sourcing operations on community-managed clusters
    email: ""
    has_organization_projects: true
    has_repository_projects: false
    location: ""
    members:
      - 4n4nd
      - aakankshaduggal
      - accorvin
      - akrawczy
      - anishasthana
      - apoorvam
      - aweiteka
      - billburnseh
      - cfchase
      - chauhankaranraj
      - christusa
      - codificat
      - coghlanRH
      - DanNiESh
      - dystewart
      - erikerlandson
      - fridex
      - gagansk
      - gmfrasca
      - Gregory-Pereira
      - harshad16
      - hbrock25
      - hemajv
      - hpdempsey
      - ipolonsk
      - isabelizimm
      - KPostOffice
      - larsks
      - laxmisravyarudraraju
      - leihchen
      - margarethaley
      - martinpovolny
      - maulikjs
      - MichaelClifford
      - mimotej
      - msdisme
      - naved001
      - oindrillac
      - op1st
      - pacospace
      - PARTHSONI95
      - quaid
      - rbo
      - redmikhail
      - riekrh
      - rimolive
      - SankBad
      - schwesig
      - Shreyanand
      - sindhuvahinis
      - skanthed
      - thegreymanshow
      - slntpts
      - TreeinRandomForest
      - caldeirav
      - vpavlin
      - suppathak
      - bryanmontalvan
    members_can_create_repositories: false
    name: Operate First
    repos:
      SRE:
        description:
          This repo contains all the SRE (Site Reliability Engineering) principles
          and guidelines for managing Operate First services
        has_projects: false
      alerts:
        default_branch: main
        description: Bots posting alerts from our clusters
        has_projects: false
      apps:
        description: Operate-first application manifests
        has_projects: false
      blueprint:
        default_branch: main
        description: This is the blueprint for the Operate First Initiative
        has_projects: false
        has_wiki: false
      common:
        default_branch: main
        description: Git Hub organization configuration
        has_projects: false
      community:
        default_branch: main
        has_projects: false
      community-handbook:
        default_branch: main
        description: Community Handbook for Operate First contributors
        has_projects: false
      continuous-delivery:
        description: Continuous Delivery
        has_projects: false
        has_wiki: false
      continuous-deployment:
        description: Continuous Deployment
        has_projects: false
        has_wiki: false
      curator:
        default_branch: main
        description: Metering project for OpenShift
        has_projects: false
      espresso-series:
        description: This is where we plan our Expresso Series Production
        has_projects: false
      example-acm-install:
        has_projects: false
      hetzner-baremetal-openshift:
        default_branch: main
        description: OpenShift 4 on Hetzner BareMetal (dedicted server)
        has_projects: false
        has_wiki: false
      hitchhikers-guide:
        default_branch: main
        description: Hitchhiker's guide to Operate-first
        has_projects: false
      installplan-operator:
        archived: true
        default_branch: main
        description: Approve manual updates using information in a configmap
        has_projects: false
      odh-dashboard:
        has_projects: false
      operate-first-twitter:
        default_branch: main
        description:
          "This repository will be used to publish tweets collaboratively  from
          the Operate First shared Twitter Account. "
        has_projects: false
        homepage: https://twitter.com/OperateFirst
      operate-first.github.io:
        has_projects: false
        has_wiki: false
      opfcli:
        default_branch: main
        has_projects: false
      schema-store:
        default_branch: main
        description: Schemas for kubernetes manifest validations
        has_projects: false
      sre-apprenticeship:
        default_branch: main
        description: Issue tracker for the SRE Apprenticeship
      support:
        default_branch: main
        description:
          This repo should serve as a central source for users to raise issues/questions/requests for Operate First.
        has_projects: false
      template:
        default_branch: main
        description: Quick template for new repositories
        has_projects: false
      toolbox:
        description: Toolbox for Operate-First tooling
        has_projects: false
      training:
        description: All training content for users and contributors
        has_projects: false
      workshop-apps:
        default_branch: main
        description: "Repository of ArgoCD application for workshop purposes "
        has_projects: false
        has_wiki: false
    teams:
      Baristas:
        description: The Espresso Series Baristas
        maintainers:
          - durandom
          - goern
        members:
          - quaid
          - MichaelClifford
          - Shreyanand
          - pacospace
          - oindrillac
          - isabelizimm
        privacy: closed
        repos:
          espresso-series: maintain
      SourceOps:
        description: This is our SourceOps team, they keep the source fresh.
        maintainers:
          - sesheta
          - op1st
        privacy: closed
        repos:
          SRE: admin
          alerts: admin
          apps: admin
          argocd-apps: admin
          blueprint: admin
          common: admin
          community: admin
          community-handbook: admin
          continuous-delivery: admin
          continuous-deployment: admin
          curator: admin
          espresso-series: admin
          example-acm-install: admin
          hetzner-baremetal-openshift: admin
          hitchhikers-guide: admin
          installplan-operator: admin
          odh-dashboard: admin
          operate-first-twitter: admin
          operate-first.github.io: admin
          opfcli: admin
          schema-store: admin
          sre-apprenticeship: admin
          support: admin
          template: admin
          toolbox: admin
          workshop-apps: admin
      admins:
        description:
          The admin team for operate-first. Members have admin access to all
          operate-first repos.
        maintainers:
          - tumido
          - HumairAK
        members:
          - 4n4nd
        privacy: closed
        repos:
          SRE: admin
          alerts: admin
          apps: admin
          argocd-apps: admin
          blueprint: admin
          common: admin
          community: admin
          community-handbook: admin
          continuous-delivery: admin
          continuous-deployment: admin
          curator: admin
          espresso-series: admin
          example-acm-install: admin
          hetzner-baremetal-openshift: admin
          hitchhikers-guide: admin
          installplan-operator: admin
          odh-dashboard: admin
          operate-first-twitter: admin
          operate-first.github.io: admin
          opfcli: admin
          schema-store: admin
          sre-apprenticeship: admin
          support: admin
          template: admin
          toolbox: admin
          workshop-apps: admin
      community-admins:
        descriptions: Admins for community oriented repos
        maintainers:
          - quaid
        members:
          - margarethaley
          - billburnseh
          - durandom
        privacy: closed
        repos:
          community: admin
          community-handbook: admin
      triagers:
        description:
          A team that can triage.
        maintainers:
          - goern
          - tumido
          - HumairAK
        members:
          - 4n4nd
          - Gregory-Pereira
          - MichaelClifford
          - Shreyanand
          - anishasthana
          - aakankshaduggal
          - billburnseh
          - chauhankaranraj
          - codificat
          - dystewart
          - erikerlandson
          - fridex
          - gagansk
          - harshad16
          - hemajv
          - hpdempsey
          - isabelizimm
          - larsks
          - leihchen
          - margarethaley
          - maulikjs
          - mimotej
          - oindrillac
          - PARTHSONI95
          - quaid
          - rbo
          - schwesig
          - suppathak
        privacy: closed
        repos:
          SRE: triage
          alerts: triage
          apps: triage
          argocd-apps: triage
          blueprint: triage
          common: triage
          community: triage
          community-handbook: triage
          continuous-delivery: triage
          continuous-deployment: triage
          curator: triage
          espresso-series: triage
          example-acm-install: triage
          hetzner-baremetal-openshift: triage
          hitchhikers-guide: triage
          installplan-operator: triage
          odh-dashboard: triage
          operate-first-twitter: triage
          operate-first.github.io: triage
          opfcli: triage
          schema-store: triage
          sre-apprenticeship: triage
          support: triage
          template: triage
          toolbox: triage
          workshop-apps: triage
      custodians:
        description: Has extra (write) permissions to be able to add issues to projects
        maintainers:
          - tumido
        members:
          - larsks
          - quaid
          - billburnseh
          - hemajv
          - harshad16
          - oindrillac
          - gagansk
          - ipolonsk
        privacy: closed
        repos:
          SRE: write
          alerts: write
          apps: write
          argocd-apps: write
          blueprint: write
          community: write
          community-handbook: write
          continuous-delivery: write
          continuous-deployment: write
          curator: write
          espresso-series: write
          example-acm-install: write
          hetzner-baremetal-openshift: write
          hitchhikers-guide: write
          installplan-operator: write
          odh-dashboard: write
          operate-first-twitter: write
          operate-first.github.io: write
          opfcli: write
          schema-store:  write
          sre-apprenticeship: write
          support: write
          template: write
          toolbox: write
          workshop-apps: write
      workshoppers:
        description: A team for members that are creating/writing workshops.
        members:
          - vpavlin
          - pacospace
        privacy: closed
        repos:
          workshop-apps: admin
      DevSecOps:
        description: A team that works on the Dev Sec operations.
        members:
          - 4n4nd
          - goern
          - Gregory-Pereira
          - harshad16
          - HumairAK
          - tumido
        privacy: closed
        repos:
          continuous-delivery: admin
      Curator:
        description: A team that works on the Curator project.
        members:
          - leihchen
          - skanthed
        privacy: closed
        repos:
          curator: write
      odh:
        description: OpenDataHub operations
        privacy: closed
        members:
          - HumairAK
          - durandom
