orgs:
  operate-first:
    admins:
      - durandom
      - goern
      - HumairAK
      - sesheta
      - tumido
    billing_email: mhild@redhat.com
    company: ""
    default_repository_permission: read
    description: Open-sourcing operations on community-managed clusters
    email: ""
    has_organization_projects: true
    has_repository_projects: false
    location: ""
    members:
      - 4n4nd
      - aakankshaduggal
      - abyrne55
      - accorvin
      - ajinkyababar
      - akcoskun
      - akrawczy
      - amfred
      - anishasthana
      - apoorvam
      - AvRajath
      - aweiteka
      - billburnseh
      - billmvt
      - brizrobbo
      - bryanmontalvan
      - caldeirav
      - carlosGimeno
      - cfchase
      - chaitanyaenr
      - chauhankaranraj
      - christusa
      - codificat
      - coghlanRH
      - DanNiESh
      - dastergon
      - david-martin
      - dofinn
      - dystewart
      - erikerlandson
      - flora177
      - fridex
      - gagansk
      - gianlucasb
      - Gkrumbach07
      - gmfrasca
      - Gregory-Pereira
      - harshad16
      - hbrock25
      - hemajv
      - hlipsig
      - hpdempsey
      - ipolonsk
      - isabelizimm
      - jacobarcarola
      - jeremyeder
      - jpweiser
      - KPostOffice
      - larsks
      - laxmisravyarudraraju
      - leihchen
      - lisa
      - margarethaley
      - martinpovolny
      - marroblee
      - maulikjs
      - mayaCostantini
      - MichaelClifford
      - mh21
      - MichaelTiemannOSC
      - mimotej
      - mmazur
      - msdisme
      - mtoslalibu
      - mubariskhan96
      - naved001
      - oindrillac
      - op1st
      - pacospace
      - PARTHSONI95
      - quaid
      - R-Lawton
      - rbo
      - redmikhail
      - rh-tmichels
      - riekrh
      - rimolive
      - roytman
      - ravitejamanepalli
      - sallyom
      - SamoKopecky
      - SankBad
      - schwesig
      - Shreyanand
      - sindhuvahinis
      - skanthed
      - slntpts
      - Spirit328
      - stefwalter
      - stefwrite
      - suppathak
      - tgau
      - thegreymanshow
      - timflannagan
      - tmicheli
      - TreeinRandomForest
      - vpavlin
      - zaoxing
      - johwes
      - mpeters
      - carlesarnal
      - ericwittmann
      - EricWittmann
      - craicoverflow
      - jsenko
      - paoloantinori
      - riprasad
      - shreekarSS
      - traytorous
      - gshahrouzi
    members_can_create_repositories: false
    name: Operate First
    repos:
      operations:
        description:
          The sig-operations repository.
        has_projects: false
      ai-for-cloud-ops:
        default_branch: main
        description: Boston University Collaboratory project for applying AI to cloud operations
        has_projects: false
      alerts:
        default_branch: main
        description: Bots posting alerts from our clusters
        has_projects: false
      apps:
        description: Operate-first application manifests
        has_projects: false
      blog:
        description: Home for blog tooling, posts, and guidelines
        has_projects: false
      blueprint:
        default_branch: main
        description: This is the blueprint for the Operate First Initiative
        has_projects: false
        has_wiki: false
      common:
        default_branch: main
        description: Git Hub organization configuration
        has_projects: false
      community:
        default_branch: main
        has_projects: false
      community-handbook:
        default_branch: main
        description: Community Handbook for Operate First contributors
        has_projects: false
      continuous-delivery:
        description: Continuous Delivery
        has_projects: false
        has_wiki: false
      continuous-deployment:
        description: Continuous Deployment
        has_projects: false
        has_wiki: false
      curator:
        default_branch: main
        description: Metering project for OpenShift
        has_projects: false
      curator-operator:
        default_branch: main
        description: Go Operator for OpenShift metrics
        has_projects: false
      espresso-series:
        description: This is where we plan our Expresso Series Production
        has_projects: false
      example-acm-install:
        has_projects: false
      hetzner-baremetal-openshift:
        default_branch: main
        description: OpenShift 4 on Hetzner BareMetal (dedicted server)
        has_projects: false
        has_wiki: false
      hitchhikers-guide:
        default_branch: main
        description: Hitchhiker's guide to Operate-first
        has_projects: false
      installplan-operator:
        archived: true
        default_branch: main
        description: Approve manual updates using information in a configmap
        has_projects: false
      ionos-openshift:
        default_branch: main
        description: IONOS HV on OpenShift
        has_projects: false
        has_wiki: false
      odh-dashboard:
        has_projects: false
      operate-first-in-action:
        default_branch: main
        description: This repository will serve as the content hub for our 2022 summit video "Operate First In Action"
        has_project: false
      operate-first-twitter:
        default_branch: main
        description:
          "This repository will be used to publish tweets collaboratively  from
          the Operate First shared Twitter Account. "
        has_projects: false
        homepage: https://twitter.com/OperateFirst
      operate-first.github.io:
        has_projects: false
        has_wiki: false
        previously:
          - website-ng
      operate-first.github.io-old:
        has_projects: false
        has_wiki: false
      opfcli:
        default_branch: main
        has_projects: false
      schema-store:
        default_branch: main
        description: Schemas for kubernetes manifest validations
        has_projects: false
      slo-evaluator:
        default_branch: main
        description: Evaluate&Store Engine for OpenSLO–defined Objectives
        has_projects: false
      sre:
        default_branch: main
        description: SRE content
        has_projects: false
      sre-u:
        default_branch: main
        description: SRE-U content
        has_projects: false
      sre-apprenticeship:
        default_branch: main
        description: Issue tracker for the SRE Apprenticeship
      support:
        default_branch: main
        description:
          This repo should serve as a central source for users to raise issues/questions/requests for Operate First.
        has_projects: false
      template:
        default_branch: main
        description: Quick template for new repositories
        has_projects: false
      toolbox:
        description: Toolbox for Operate-First tooling
        has_projects: false
      training:
        description: All training content for users and contributors
        has_projects: false
      workshop-apps:
        default_branch: main
        description: "Repository of ArgoCD application for workshop purposes "
        has_projects: false
        has_wiki: false
    teams:
      Baristas:
        description: The Espresso Series Baristas
        maintainers:
          - durandom
          - goern
        members:
          - quaid
          - MichaelClifford
          - Shreyanand
          - pacospace
          - oindrillac
          - isabelizimm
        privacy: closed
        repos:
          espresso-series: maintain
      SourceOps:
        description: This is our SourceOps team, they keep the source fresh.
        maintainers:
          - sesheta
          - op1st
        privacy: closed
        repos:
          operations: admin
          alerts: admin
          apps: admin
          argocd-apps: admin
          blueprint: admin
          common: admin
          community: admin
          community-handbook: admin
          continuous-delivery: admin
          continuous-deployment: admin
          curator: admin
          curator-operator: admin
          espresso-series: admin
          example-acm-install: admin
          hetzner-baremetal-openshift: admin
          hitchhikers-guide: admin
          installplan-operator: admin
          ionos-openshift: admin
          odh-dashboard: admin
          operate-first-twitter: admin
          operate-first.github.io: admin
          operate-first.github.io-old: admin
          opfcli: admin
          schema-store: admin
          sre-apprenticeship: admin
          support: admin
          template: admin
          toolbox: admin
          workshop-apps: admin
      admins:
        description:
          The admin team for operate-first. Members have admin access to all
          operate-first repos.
        maintainers:
          - tumido
          - HumairAK
        members:
          - 4n4nd
        privacy: closed
        repos:
          operations: admin
          alerts: admin
          apps: admin
          argocd-apps: admin
          blueprint: admin
          common: admin
          community: admin
          community-handbook: admin
          continuous-delivery: admin
          continuous-deployment: admin
          curator: admin
          curator-operator: admin
          espresso-series: admin
          example-acm-install: admin
          hetzner-baremetal-openshift: admin
          hitchhikers-guide: admin
          installplan-operator: admin
          ionos-openshift: admin
          odh-dashboard: admin
          operate-first-twitter: admin
          operate-first.github.io: admin
          operate-first.github.io-old: admin
          opfcli: admin
          schema-store: admin
          sre-apprenticeship: admin
          support: admin
          template: admin
          toolbox: admin
          training: admin
          workshop-apps: admin
      ai-for-cloud-ops:
        description: A team maintaining AI for cloud ops collaboratory projects.
        members:
          - akcoskun
          - zaoxing
          - gianlucasb
          - abyrne55
          - mtoslalibu
        privacy: closed
        repos:
          ai-for-cloud-ops: admin
      blog:
        description: Writers and reviewers of Op1st blog posts
        privacy: closed  # Keep as closed, more info: https://docs.github.com/en/rest/reference/teams#create-a-team
        maintainers:
          - quaid
          - jeremyeder
          - mhild
          - mmazur
        members:
          - aakankshaduggal
          - akrawczy
          - amfred
          - billburnseh
          - bryanmontalvan
          - coghlanRH
          - david-martin
          - hemajv
          - hpdempsey
          - jeremyeder
          - larsks
          - margarethaley
          - MichaelClifford
          - MichaelTiemannOSC
          - mmazur
          - msdisme
          - oindrillac
          - quaid
          - R-Lawton
          - sallyom
          - schwesig
          - stefwalter
          - stefwrite
        repos:
          blog: triage
      blog-editorial:
        description: Editors who are allowed to edit and publish blog posts
        privacy: closed
        maintainers:
          - quaid
          - jeremyeder
          - mhild
          - mmazur
        members:
          - quaid
          - coghlanRH
          - jeremyeder
          - stefwrite
        repos:
            blog: write
      blog-publishers:
        description: Team that can rework the blog platform and make ultimate publishing decisions
        privacy: closed
        maintainers:
          - durandom
          - quaid
        repos:
          blog: admin
      community-admins:
        descriptions: Admins for community oriented repos
        maintainers:
          - quaid
        members:
          - margarethaley
          - billburnseh
          - durandom
        privacy: closed
        repos:
          community: admin
          community-handbook: admin
      triagers:
        description:
          A team that can triage.
        maintainers:
          - goern
          - tumido
          - HumairAK
        members:
          - 4n4nd
          - Gregory-Pereira
          - MichaelClifford
          - Shreyanand
          - anishasthana
          - aakankshaduggal
          - billburnseh
          - chauhankaranraj
          - codificat
          - dystewart
          - erikerlandson
          - fridex
          - gagansk
          - harshad16
          - hemajv
          - hpdempsey
          - isabelizimm
          - larsks
          - leihchen
          - margarethaley
          - maulikjs
          - mimotej
          - oindrillac
          - PARTHSONI95
          - quaid
          - rbo
          - schwesig
          - suppathak
        privacy: closed
        repos:
          operations: triage
          alerts: triage
          apps: triage
          argocd-apps: triage
          blueprint: triage
          common: triage
          community: triage
          community-handbook: triage
          continuous-delivery: triage
          continuous-deployment: triage
          curator: triage
          curator-operator: triage
          espresso-series: triage
          example-acm-install: triage
          hetzner-baremetal-openshift: triage
          hitchhikers-guide: triage
          installplan-operator: triage
          ionos-openshift: admin
          odh-dashboard: triage
          operate-first-twitter: triage
          operate-first.github.io: triage
          operate-first.github.io-old: triage
          opfcli: triage
          schema-store: triage
          sre-apprenticeship: triage
          support: triage
          template: triage
          toolbox: triage
          training: triage
          workshop-apps: triage
      custodians:
        description: Has extra (write) permissions to be able to add issues to projects
        maintainers:
          - tumido
        members:
          - larsks
          - quaid
          - billburnseh
          - hemajv
          - harshad16
          - oindrillac
          - gagansk
          - Gregory-Pereira
          - dystewart
        privacy: closed
        repos:
          operations: write
          alerts: write
          apps: write
          argocd-apps: write
          blueprint: write
          community: write
          community-handbook: write
          continuous-delivery: write
          continuous-deployment: write
          curator: write
          curator-operator: write
          espresso-series: write
          example-acm-install: write
          hetzner-baremetal-openshift: write
          hitchhikers-guide: write
          installplan-operator: write
          ionos-openshift: admin
          odh-dashboard: write
          operate-first-twitter: write
          operate-first.github.io: write
          operate-first.github.io-old: write
          opfcli: write
          schema-store:  write
          sre-apprenticeship: write
          support: write
          template: write
          toolbox: write
          workshop-apps: write
      workshoppers:
        description: A team for members that are creating/writing workshops.
        members:
          - vpavlin
          - pacospace
        privacy: closed
        repos:
          workshop-apps: admin
      DevSecOps:
        description: A team that works on the Dev Sec operations.
        members:
          - 4n4nd
          - goern
          - Gregory-Pereira
          - harshad16
          - HumairAK
          - tumido
        privacy: closed
        repos:
          common: admin
          continuous-delivery: admin
      Curator:
        description: A team that works on the Curator project.
        members:
          - leihchen
          - skanthed
          - ajinkyababar
          - timflannagan
          - AvRajath
        privacy: closed
        repos:
          curator: write
          curator-operator: write
      odh:
        description: OpenDataHub operations
        privacy: closed
        members:
          - HumairAK
          - durandom
          - 4n4nd
          - Gkrumbach07
          - Gregory-Pereira
          - harshad16
        repos:
          odh-manifests: admin
      training:
        description: Manage all training content for users and contributors
        privacy: closed
        members:
          - stefwrite
        repos:
          training: admin
      sre:
        description: A team maintaining SRE–related projects.
        members:
          - david-martin
          - jeremyeder
          - lisa
          - mmazur
        privacy: closed
        repos:
          slo-evaluator: admin
          sre: admin
      ionos-openshift:
        description: A team maintaining the IONOS OpenShift project
        members:
          - durandom
          - schwesig
          - tmicheli
        privacy: closed
        repos:
          ionos-openshift: admin
      operate-first-in-action:
        description: A team maintaining the Operate First in Action repo
        members:
          - durandom
          - schwesig
          - michaelclifford
          - oindrillac
          - aakankshaduggal
          - goern
          - tumido
        privacy: closed
        repos:
          operate-first-in-action: admin
      sre-u:
        description: A team maintaining the Operate First, Red Hat SRE-U training
        members:
          - marroblee
          - hlipsig
        privacy: closed
        repos:
          sre-u: admin
